# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w0VdvfIe79kZmOuYfUZWqS_ROfz1JqN9
"""

import streamlit as st
import joblib
import pandas as pd

# =========================
# CARGAR MODELO
# =========================

modelo = joblib.load("modelo.pkl")

# =========================
# INTERFAZ
# =========================

st.title("Predicción de Alta Demanda para Repartidores")

st.write(
    "Esta aplicación ayuda a identificar "
    "horarios con alta demanda de pedidos."
)

# =========================
# INPUTS
# =========================

mes = st.number_input(
    "Mes",
    min_value=1,
    max_value=12
)

dia = st.number_input(
    "Día",
    min_value=1,
    max_value=31
)

hora = st.number_input(
    "Horario",
    min_value=0,
    max_value=23
)

# =========================
# PREDICCIÓN
# =========================

if st.button("Analizar Demanda"):

    datos = pd.DataFrame({
        'Mes': [mes],
        'Día': [dia],
        'HorarioXhora': [hora]
    })

    prediccion = modelo.predict(datos)

    if prediccion[0] == 1:

        st.error(
            "Alta Demanda: momento conveniente para trabajar."
        )

    else:

        st.success(
            "Demanda Normal."
        )