# -*- coding: utf-8 -*-
"""Avance 3 TIF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2_jMxxvVgjuR2ntBpC-24xgEt1we987

# LIBRERÍAS Y CONFIGURACIÓN
"""

# Importación de librerías necesarias según el Ciclo 1 (Scikit-learn)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score, recall_score, precision_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import warnings
warnings.filterwarnings('ignore')

print("✅ Librerías importadas correctamente.")

"""# CARGA DEL DATASET"""

# ============================================================================
# CARGA MANUAL DEL ARCHIVO EXCEL
# ============================================================================
print("📁 SUBIR ARCHIVO EXCEL")
print("="*60)
print("Hacé clic en 'Choose Files' y seleccioná tu archivo Excel")
print("="*60)

# Subir archivo
uploaded = files.upload()

# Verificar que se haya subido un archivo
if uploaded:
    archivo_nombre = list(uploaded.keys())[0]
    print(f"\n✅ Archivo cargado: {archivo_nombre}")

    # Cargar el dataset
    df = pd.read_excel(archivo_nombre, sheet_name='Hoja1')

    # Limpieza de datos
    df = df.dropna(subset=['PedidosHechos'])
    df = df.reset_index(drop=True)

    # Eliminar columna Fecha si existe
    if 'Fecha' in df.columns:
        df.drop(columns=['Fecha'], inplace=True)

    print(f"\n📊 Dataset cargado exitosamente:")
    print(f"   - Registros: {df.shape[0]}")
    print(f"   - Columnas: {df.shape[1]}")
    print(f"\n📋 Primeras filas:")
    df.head(10)

else:
    print("❌ No se subió ningún archivo. Por favor, ejecutá la celda nuevamente.")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================================================
# DEFINICIÓN DEL TARGET (Alta Demanda y Nivel de Demanda Categórico)
# ============================================================================
# Según el problema del Word:
# Clasificar en "Alta Demanda" vs "Demanda Normal" (binary target)
# Además, visualizar "Baja Demanda" para PedidosHechos = 0

# Binary Target (AltaDemanda):
df['AltaDemanda'] = (df['PedidosHechos'] >= 2).astype(int)

# Categorical variable for visualization (NivelDemandaCategorico):
def categorizar_nivel_demanda(pedidos):
    if pedidos == 0:
        return 'Baja Demanda'
    elif pedidos == 1:
        return 'Demanda Normal'
    else: # pedidos >= 2
        return 'Alta Demanda'

df['NivelDemandaCategorico'] = df['PedidosHechos'].apply(categorizar_nivel_demanda)

print("🎯 VARIABLE OBJETIVO (Target) - Binario")
print("="*60)
print("Criterio: PedidosHechos < 2 → DEMANDA NORMAL (0)")
print("Criterio: PedidosHechos >= 2 → ALTA DEMANDA (1)")
print("="*60)
print("\n📈 Distribución de clases (Binario):")
print(df['AltaDemanda'].value_counts())
print(f"\nProporción (Binario):")
print(f"  - Demanda Normal (0): {(df['AltaDemanda']==0).sum()} registros ({(df['AltaDemanda']==0).mean()*100:.1f}%)")
print(f"  - Alta Demanda (1): {(df['AltaDemanda']==1).sum()} registros ({(df['AltaDemanda']==1).mean()*100:.1f}%)")

print("\n\n🎯 NIVELES DE DEMANDA (Para Visualización)")
print("="*60)
print("Criterio: PedidosHechos = 0 → BAJA DEMANDA")
print("Criterio: PedidosHechos = 1 → DEMANDA NORMAL")
print("Criterio: PedidosHechos >= 2 → ALTA DEMANDA")
print("="*60)
print("\n📈 Distribución de niveles de demanda (Categórico):")
print(df['NivelDemandaCategorico'].value_counts())
print(f"\nProporción (Categórico):")
baja_demanda_count = (df['NivelDemandaCategorico'] == 'Baja Demanda').sum()
normal_demanda_categorico_count = (df['NivelDemandaCategorico'] == 'Demanda Normal').sum()
alta_demanda_categorico_count = (df['NivelDemandaCategorico'] == 'Alta Demanda').sum()
total_records = df.shape[0]

print(f"  - Baja Demanda: {baja_demanda_count} registros ({baja_demanda_count/total_records*100:.1f}%)")
print(f"  - Demanda Normal: {normal_demanda_categorico_count} registros ({normal_demanda_categorico_count/total_records*100:.1f}%)")
print(f"  - Alta Demanda: {alta_demanda_categorico_count} registros ({alta_demanda_categorico_count/total_records*100:.1f}%)")

# Visualización
plt.figure(figsize=(10, 6)) # Increased figure size for better readability
sns.countplot(data=df, x='NivelDemandaCategorico', palette='viridis',
              order=['Baja Demanda', 'Demanda Normal', 'Alta Demanda']) # Specify order for consistent plotting
plt.title('Distribución de Clases de Demanda')
plt.ylabel('Cantidad de registros')
plt.xlabel('Clase de Demanda')
plt.show()

def clasificar_demanda(pedidos):
    if pedidos == 0:
        return "Baja"
    elif pedidos == 1:
        return "Normal"
    else:
        return "Alta"

df["NivelDemanda"] = df["PedidosHechos"].apply(clasificar_demanda)

X = df[["Mes","Día","HorarioXhora"]]
y = df["NivelDemanda"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

modelo = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

modelo.fit(X_train, y_train)

print(y.unique())
print(y.dtype)

df["NivelDemanda"].value_counts()

X = df[["Mes","Día","HorarioXhora"]]
y = df["NivelDemanda"]

"""Entrenamos el modelo"""

X = df[["Mes", "Día", "HorarioXhora"]]
y = df["NivelDemanda"]

print(modelo.classes_)

#EVALUAMOS EL MODELO

from sklearn.metrics import classification_report

pred = modelo.predict(X_test)

print(classification_report(y_test, pred))

"""Predicción Interactiva"""

mes = int(input("Mes: "))
dia = int(input("Día: "))
hora = int(input("Hora: "))

nuevo = pd.DataFrame({
    "Mes":[mes],
    "Día":[dia],
    "HorarioXhora":[hora]
})

prediccion = modelo.predict(nuevo)[0]

print("Nivel de demanda esperado:", prediccion)


probabilidades = modelo.predict_proba(nuevo)[0]

for clase, prob in zip(modelo.classes_, probabilidades):
    print(f"{clase}: {prob*100:.2f}%")


if prediccion == "Alta":
    print("🟢 Se recomienda trabajar en este horario.")
elif prediccion == "Normal":
    print("🟡 Existe una demanda moderada.")
else:
    print("🔴 No se recomienda trabajar en este horario.")

### CARGA DEL DATASET


from google.colab import files

uploaded = files.upload()

### INSTALACIÓN DE LIBRERÍAS
!pip install streamlit joblib openpyxl -q

### ENTRENAR Y GUARDAR MODELO

import pandas as pd
import joblib
from sklearn.ensemble import RandomForestClassifier


# CARGAR DATASET
df = pd.read_excel("DATASET TIF.xlsx")


# VER COLUMNAS
print(df.columns)


# VARIABLES
X = df[['Mes', 'Día', 'HorarioXhora']]
y = df['PedidosHechos']


# ENTRENAR MODELO
modelo = RandomForestClassifier()
modelo.fit(X, y)


# GUARDAR MODELO
joblib.dump(modelo, "modelo.pkl")
print("Modelo guardado correctamente")

# Commented out IPython magic to ensure Python compatibility.
# ### CREACIÓN DE LA APP.PY
# 
# %%writefile app.py
# 
# import streamlit as st
# import joblib
# import pandas as pd
# 
# 
# # CARGAR MODELO
# modelo = joblib.load("modelo.pkl")
# 
# # INTERFAZ
# st.title("Predicción de Pedidos")
# 
# st.write("Ingrese los datos para realizar la predicción.")
# 
# # INPUTS
# mes = st.number_input(
#     "Mes",
#     min_value=1,
#     max_value=12
# )
# 
# dia = st.number_input(
#     "Día",
#     min_value=1,
#     max_value=31
# )
# 
# hora = st.number_input(
#     "Horario por Hora",
#     min_value=0,
#     max_value=23
# )
# 
# 
# # PREDICCIÓN
# if st.button("Predecir"):
# 
#     datos = pd.DataFrame({
#         'Mes': [mes],
#         'Día': [dia],
#         'HorarioXhora': [hora]
#     })
# 
#     prediccion = modelo.predict(datos)
# 
#     st.success(
#         f"Pedidos estimados: {prediccion[0]}"
#     )

###EJECUCIÓN DEL STREAMLIT
!streamlit run app.py

"""CREACIÓN DEL README"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md
# 
# # Predicción de Pedidos con Streamlit
# 
# ## Descripción
# Este proyecto utiliza Machine Learning para predecir la cantidad de pedidos realizados en función del mes, día y horario.
# 
# La aplicación fue desarrollada con Streamlit y el modelo fue entrenado con RandomForestClassifier.
# 
# ---
# 
# ## Tecnologías utilizadas
# 
# - Python
# - Pandas
# - Scikit-learn
# - Streamlit
# - Joblib
# 
# ---
# 
# ## Archivos del proyecto
# 
# - `Avance_3_TIF.ipynb` → Notebook principal
# - `app.py` → Aplicación Streamlit
# - `modelo.pkl` → Modelo entrenado
# - `DATASET TIF.xlsx` → Dataset utilizado
# 
# ---
# 
# ## Instalación
# 
# Instalar las librerías necesarias:
# 
# ```bash
# pip install streamlit pandas scikit-learn joblib openpyxl
#

#DESCARGA DE README
from google.colab import files

files.download("README.md")

!streamlit run app.py

###DESCARGA DEL MODELO PKL

from google.colab import files

files.download("modelo.pkl")

"""AVANCE 4"""

#METRICAS COMPLETAS

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    classification_report,
    roc_curve,
    auc
)

import matplotlib.pyplot as plt

# =========================
# VARIABLE OBJETIVO
# =========================

df['AltaDemanda'] = (df['PedidosHechos'] >= 2).astype(int)

X = df[['Mes', 'Día', 'HorarioXhora']]
y = df['AltaDemanda']

# =========================
# TRAIN TEST SPLIT
# =========================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

# =========================
# MODELO
# =========================

modelo = RandomForestClassifier(random_state=42)

modelo.fit(X_train, y_train)

# =========================
# PREDICCIONES
# =========================

y_pred = modelo.predict(X_test)

# =========================
# MÉTRICAS
# =========================

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# MATRIZ DE CONFUSION

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)

disp.plot()

plt.title("Matriz de Confusión")

plt.show()

#CURVA ROC

y_probs = modelo.predict_proba(X_test)[:,1]

fpr, tpr, thresholds = roc_curve(y_test, y_probs)

roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")

plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel("False Positive Rate")

plt.ylabel("True Positive Rate")

plt.title("Curva ROC")

plt.legend()

plt.show()

"""EXPLICAVILIDAD DEL MODELO"""

#IMPORTANCIA DE FEATURES

import pandas as pd

importancias = modelo.feature_importances_

features = X.columns

df_importancia = pd.DataFrame({
    'Variable': features,
    'Importancia': importancias
})

print(df_importancia)

df_importancia.sort_values(
    by='Importancia',
    ascending=False
).plot(
    x='Variable',
    y='Importancia',
    kind='bar'
)

plt.title("Importancia de Variables")

plt.ylabel("Importancia")

plt.show()

"""El modelo considera que el horario es la variable más importante para detectar alta demanda, lo cual coincide con los horarios pico de almuerzo y cena.

¿Qué hace el sistema?

Este sistema ayuda a repartidores de plataformas digitales a identificar los horarios con mayor demanda de pedidos utilizando datos históricos del último año.

El usuario ingresa un día, mes y horario, y el sistema predice si existe una alta probabilidad de demanda elevada en ese momento.

¿Qué tan confiable es?

El modelo fue entrenado utilizando técnicas de Machine Learning supervisado y evaluado con métricas como accuracy, recall y F1-score.

Los resultados muestran que el sistema logra identificar correctamente gran parte de los momentos de alta demanda utilizando patrones histórico

¿Qué NO puede hacer?

El sistema no puede predecir eventos inesperados como:

tormentas,
promociones especiales,
feriados excepcionales,
caídas de plataformas,
cambios repentinos en el comportamiento de los usuarios.

Las predicciones se basan únicamente en datos históricos.

ANALISIS Y LIMITES DE RIESGOS

Cambios inesperados en la demanda
**texto en negrita**
El modelo puede fallar ante eventos no presentes en el dataset histórico, como promociones especiales, condiciones climáticas extremas o eventos masivos.

En esos casos, la demanda real puede ser muy distinta a la predicha.



--------------------
**Dataset limitado**

El sistema fue entrenado con información de un único repartidor y un período específico.

Por lo tanto, los patrones aprendidos pueden no representar el comportamiento general de todas las zonas o plataformas.


**Horarios atípicos**

El modelo puede equivocarse en horarios poco frecuentes o con pocos datos históricos, debido a la falta de ejemplos suficientes durante el entrenamiento.
"""

# Commented out IPython magic to ensure Python compatibility.
# #Crear requirements.txt
# 
# %%writefile requirements.txt
# 
# streamlit
# pandas
# scikit-learn
# joblib
# openpyxl

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import joblib
# import pandas as pd
# 
# # =========================
# # CARGAR MODELO
# # =========================
# 
# modelo = joblib.load("modelo.pkl")
# 
# # =========================
# # INTERFAZ
# # =========================
# 
# st.title("Predicción de Alta Demanda para Repartidores")
# 
# st.write(
#     "Esta aplicación ayuda a identificar "
#     "horarios con alta demanda de pedidos."
# )
# 
# # =========================
# # INPUTS
# # =========================
# 
# mes = st.number_input(
#     "Mes",
#     min_value=1,
#     max_value=12
# )
# 
# dia = st.number_input(
#     "Día",
#     min_value=1,
#     max_value=31
# )
# 
# hora = st.number_input(
#     "Horario",
#     min_value=0,
#     max_value=23
# )
# 
# # =========================
# # PREDICCIÓN
# # =========================
# 
# if st.button("Analizar Demanda"):
# 
#     datos = pd.DataFrame({
#         'Mes': [mes],
#         'Día': [dia],
#         'HorarioXhora': [hora]
#     })
# 
#     prediccion = modelo.predict(datos)
# 
#     if prediccion[0] == 1:
# 
#         st.error(
#             "Alta Demanda: "
#             "momento conveniente para trabajar."
#         )
# 
#     else:
# 
#         st.success(
#             "Demanda Normal."
#         )

###app.py

import streamlit as st
import joblib
import pandas as pd

# =========================
# CARGAR MODELO
# =========================

modelo = joblib.load("modelo.pkl")

# =========================
# INTERFAZ
# =========================

st.title("Predicción de Alta Demanda para Repartidores")

st.write(
    "Esta aplicación ayuda a identificar "
    "horarios con alta demanda de pedidos."
)

# =========================
# INPUTS
# =========================

mes = st.number_input(
    "Mes",
    min_value=1,
    max_value=12
)

dia = st.number_input(
    "Día",
    min_value=1,
    max_value=31
)

hora = st.number_input(
    "Horario",
    min_value=0,
    max_value=23
)

# =========================
# PREDICCIÓN
# =========================

if st.button("Analizar Demanda"):

    datos = pd.DataFrame({
        'Mes': [mes],
        'Día': [dia],
        'HorarioXhora': [hora]
    })

    prediccion = modelo.predict(datos)

    if prediccion[0] == 1:

        st.error(
            "Alta Demanda: momento conveniente para trabajar."
        )

    else:

        st.success(
            "Demanda Normal."
        )

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# ...

